server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          username: LuisL96
          password: Lozano96@#
          default-label: circuit-breaker
          uri: https://github.com/LuisL96/microservicios-tutorial
          search-paths: config-data
  application:
    name: config-service
